"use client";

import { useEffect, useState } from "react";
import { BarChart3, Box, DollarSign, ShoppingCart, Users } from "lucide-react";
import { apiFetch as fetch } from "../../../lib/api";

export default function AnalyticsPage() {
  const [data, setData] = useState(null);
  useEffect(() => { fetch("/api/admin/analytics").then((response) => response.json()).then((result) => result.success && setData(result.analytics)); }, []);
  const metrics = [{ label: "Revenue", value: `$${Number(data?.revenue || 0).toFixed(2)}`, icon: DollarSign, color: "text-emerald-600", background: "bg-emerald-50" }, { label: "Orders", value: data?.orders ?? "-", icon: ShoppingCart, color: "text-orange-500", background: "bg-orange-50" }, { label: "Customers", value: data?.customers ?? "-", icon: Users, color: "text-fuchsia-500", background: "bg-fuchsia-50" }, { label: "Products", value: data?.products ?? "-", icon: Box, color: "text-[#2164d8]", background: "bg-blue-50" }];
  return <div className="mx-auto max-w-[1180px] space-y-6"><div><h1 className="text-2xl font-extrabold text-[#111a32]">Analytics</h1><p className="mt-1 text-sm text-[#607492]">Review storefront performance and operational activity.</p></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, icon: Icon, color, background }) => <div key={label} className="rounded-[22px] border border-slate-200 bg-white p-6 shadow-[0_8px_30px_rgba(20,37,63,0.04)]"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#91a3c1]">{label}</span><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${background} ${color}`}><Icon size={19} /></div></div><p className="mt-5 text-3xl font-extrabold text-[#111a32]">{value}</p><p className="mt-1 text-xs text-slate-400">Current database total</p></div>)}</div><section className="rounded-[22px] border border-slate-200 bg-white p-7 shadow-[0_8px_30px_rgba(20,37,63,0.04)]"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-[#2164d8]"><BarChart3 size={19} /></div><div><h2 className="text-lg font-extrabold text-[#111a32]">Order Status Analysis</h2><p className="text-xs text-slate-400">Distribution of current customer orders.</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{["Pending", "Processing", "Shipped", "Delivered", "Cancelled"].map((status) => { const item = data?.byStatus?.find((entry) => entry._id === status); return <div key={status} className="rounded-xl bg-slate-50 p-5"><p className="text-xs font-bold text-slate-500">{status}</p><p className="mt-2 text-2xl font-extrabold text-[#111a32]">{item?.count || 0}</p></div>; })}</div></section></div>;
}
