export const categories = [
  { id: "all", label: "All Products" },
  { id: "laser", label: "Laser Printers" },
  { id: "inkjet", label: "Inkjet & EcoTank" },
  { id: "all-in-one", label: "All-in-One Multi-Function" },
  { id: "supplies", label: "Ink & Toners" },
];

export const brands = ["All Brands", "HP", "Canon", "Epson", "Brother"];

export const products = [
  {
    id: "hp-laserjet-pro-mfp-3101fdwe",
    name: "HP LaserJet Pro MFP 3101fdwe All-in-One Wireless Monochrome Printer",
    brand: "HP",
    category: "laser",
    price: 269.99,
    originalPrice: 329.99,
    rating: 4.8,
    reviewsCount: 142,
    inStock: true,  
    stockCount: 18,
    badge: "Best Seller",
    image: "/hp-printer4.png",
    fallbackColor: "#024AD8",
    shortDesc: "Fast black-and-white printing, automatic two-sided scanning, copy, and secure Wi-Fi for busy home offices and small teams.",
    features: [
      "Print speeds up to 35 ppm",
      "Automatic 2-sided printing & scanning",
      "Dual-band Wi-Fi with self-healing",
      "Includes 3 months of HP Instant Ink",
    ],
    specs: {
      printSpeed: "Up to 35 ppm (Black)",
      connectivity: "Dual-band Wi-Fi, Ethernet, USB 2.0, Bluetooth LE",
      trayCapacity: "250-sheet input tray",
      functions: "Print, Copy, Scan, Fax",
      warranty: "1-Year Official HP Commercial Warranty",
      resolution: "1200 x 1200 dpi",
    },
  },
  {
    id: "epson-ecotank-et-2850",
    name: "Epson EcoTank ET-2850 Cartridge-Free Supertank Color All-in-One Printer",
    brand: "Epson",
    category: "inkjet",
    price: 249.99,
    originalPrice: 299.99,
    rating: 4.9,
    reviewsCount: 318,
    inStock: true,
    stockCount: 24,
    badge: "Most Popular",
    image: "/printer-support-hero.png",
    fallbackColor: "#0066CC",
    shortDesc: "Innovative cartridge-free printing with supersized ink tanks. Includes up to 2 years of ink in the box, saving up to 90% on replacement ink.",
    features: [
      "High-yield printing with replacement ink bottles",
      "Auto 2-sided printing & high-res flatbed scanner",
      "Stress-free bottle filling with keyed auto-stop bottles",
      "Epson Smart Panel app for phone setup",
    ],
    specs: {
      printSpeed: "10.5 ppm (Black), 5.0 ppm (Color)",
      connectivity: "Wi-Fi, Wi-Fi Direct, USB",
      trayCapacity: "100-sheet rear feeder",
      functions: "Print, Copy, Scan",
      warranty: "2-Year Limited Manufacturer Warranty (with registration)",
      resolution: "4800 x 1200 optimized dpi",
    },
  },
  {
    id: "brother-hl-l2370dw",
    name: "Brother HL-L2370DW Compact Wireless Monochrome Laser Printer",
    brand: "Brother",
    category: "laser",
    price: 159.99,
    originalPrice: 189.99,
    rating: 4.7,
    reviewsCount: 205,
    inStock: true,
    stockCount: 15,
    badge: "Top Value",
    image: "/hp-support2.png",
    fallbackColor: "#003399",
    shortDesc: "Class-leading print speeds up to 36 ppm with automatic duplex printing and flexible wireless mobile device connectivity.",
    features: [
      "Engineered for high productivity up to 36 ppm",
      "Automatic duplex (2-sided) printing",
      "250-sheet paper capacity handles letter or legal paper",
      "AirPrint, Google Cloud Print, Brother iPrint&Scan",
    ],
    specs: {
      printSpeed: "Up to 36 ppm",
      connectivity: "Wireless 802.11 b/g/n, Ethernet, Hi-Speed USB 2.0",
      trayCapacity: "250-sheet paper tray",
      functions: "High-Speed Laser Printing",
      warranty: "1-Year Limited Warranty with Free Machine-Lifetime Support",
      resolution: "2400 x 600 dpi class",
    },
  },
  {
    id: "canon-pixma-megatank-g3270",
    name: "Canon PIXMA MegaTank G3270 All-in-One Wireless Inkjet Printer",
    brand: "Canon",
    category: "inkjet",
    price: 179.99,
    originalPrice: 229.99,
    rating: 4.6,
    reviewsCount: 94,
    inStock: true,
    stockCount: 11,
    badge: "Popular Pick",
    image: "/printer-support-hero1.png",
    fallbackColor: "#CC0000",
    shortDesc: "Built for high-volume, cost-effective photo and document printing with refillable high-yield MegaTank ink reservoirs.",
    features: [
      "Huge page yield: up to 6,000 black / 7,700 color pages per set",
      "1.35-inch square LCD screen for intuitive operation",
      "Crisp text and borderless photo printing up to 8.5 x 11 inches",
      "Easy maintenance cartridge user-replaceable",
    ],
    specs: {
      printSpeed: "11.0 ipm (Black), 6.0 ipm (Color)",
      connectivity: "Wi-Fi, USB, Apple AirPrint, Mopria",
      trayCapacity: "100-sheet rear paper tray",
      functions: "Print, Copy, Scan",
      warranty: "1-Year Canon Limited Warranty with InstantExchange",
      resolution: "4800 x 1200 dpi",
    },
  },
  {
    id: "hp-officejet-pro-9125e",
    name: "HP OfficeJet Pro 9125e All-in-One Wireless Color Inkjet Commercial Printer",
    brand: "HP",
    category: "all-in-one",
    price: 289.99,
    originalPrice: 349.99,
    rating: 4.8,
    reviewsCount: 177,
    inStock: true,
    stockCount: 9,
    badge: "Office Pick",
    image: "/hp-support3.png",
    fallbackColor: "#024AD8",
    shortDesc: "Commercial-grade performance with fast color speeds, automated two-sided scanning, robust security, and smart cloud printing.",
    features: [
      "Fast color printing up to 22 ppm black / 18 ppm color",
      "Single-pass 2-sided automatic document feeder (35 sheets)",
      "HP Wolf Pro Security embedded with multi-layered defense",
      "Quiet mode for focused workspace environments",
    ],
    specs: {
      printSpeed: "22 ppm (Black), 18 ppm (Color)",
      connectivity: "Self-healing Dual-Band Wi-Fi, Gigabit Ethernet, USB",
      trayCapacity: "250-sheet input tray + 60-sheet output",
      functions: "Print, Scan, Copy, Fax",
      warranty: "Up to 2-Year HP Commercial Warranty",
      resolution: "Up to 4800 x 1200 optimized dpi",
    },
  },
  {
    id: "brother-tn760-toner-high-yield",
    name: "Brother Genuine TN760 High-Yield Black Toner Cartridge",
    brand: "Brother",
    category: "supplies",
    price: 79.99,
    originalPrice: 89.99,
    rating: 4.9,
    reviewsCount: 520,
    inStock: true,
    stockCount: 42,
    badge: "Certified Genuine",
    image: "/customer-care.jpg",
    fallbackColor: "#0137a7",
    shortDesc: "Authentic Brother high-yield black toner formulated to produce rich, sharp laser printouts without smudging or fading.",
    features: [
      "Yields approximately 3,000 pages",
      "Seamlessly engineered for Brother laser printers",
      "Consistent, smudge-proof professional text clarity",
      "Eco-conscious recycling program available",
    ],
    specs: {
      pageYield: "Approx. 3,000 pages (ISO/IEC 19752)",
      compatibility: "HL-L2350DW, HL-L2370DW, DCP-L2550DW, MFC-L2710DW, MFC-L2750DW",
      color: "Monochrome Black",
      warranty: "Brother Genuine Replacement Guarantee",
    },
  },
  {
    id: "hp-67xl-high-yield-combo-ink",
    name: "HP 67XL High-Yield Black & Tri-Color Original Ink Cartridges Combo",
    brand: "HP",
    category: "supplies",
    price: 54.99,
    originalPrice: 62.99,
    rating: 4.7,
    reviewsCount: 389,
    inStock: true,
    stockCount: 35,
    badge: "Essential",
    image: "/svg-icon.png",
    fallbackColor: "#024AD8",
    shortDesc: "High-capacity Original HP Ink cartridges formulated to deliver vibrant photos and crisp, clean everyday documents.",
    features: [
      "Up to 2x more prints compared to standard cartridges",
      "Fade-resistant pigments for long-lasting archival quality",
      "Recycled plastic construction with free closed-loop recycling",
      "Smart ink level tracking alerts before you run out",
    ],
    specs: {
      pageYield: "Black ~240 pages, Tri-Color ~200 pages",
      compatibility: "HP ENVY 6000, 6400 series, DeskJet 2700, 4100 series",
      colors: "1 Black XL + 1 Tri-Color XL Cartridge",
      warranty: "HP Ink & Toner Quality Guarantee",
    },
  },
  {
    id: "smarteprint-gold-plated-printer-cable-10ft",
    name: "HP Certified Pro High-Speed USB 2.0 Gold-Plated Printer Cable (10ft)",
    brand: "HP",
    category: "accessories",
    price: 18.99,
    originalPrice: 24.99,
    rating: 4.9,
    reviewsCount: 164,
    inStock: true,
    stockCount: 50,
    badge: "Recommended",
    image: "/svg-icon.png",
    fallbackColor: "#3B82F6",
    shortDesc: "Heavy-duty shielded USB Type-A to Type-B male cable with gold-plated connectors for zero-latency, error-free printing.",
    features: [
      "Gold-plated corrosion-resistant connectors",
      "Double-braided nylon exterior rated for 15,000+ bends",
      "High-speed data transfer up to 480 Mbps",
      "Universal plug-and-play compatibility with HP, Canon, Epson, Brother",
    ],
    specs: {
      length: "10 Feet (3 Meters)",
      connectors: "USB 2.0 Type-A Male to Type-B Male",
      shielding: "Multi-layer foil & braid shielding against EMI/RFI noise",
      warranty: "Lifetime Replacement Warranty",
    },
  },
];
