export const categories = [
  { id: "all", label: "Shop All Products" },
  { id: "home-printers", label: "Home Printers" },
  { id: "office-printers", label: "Office Printers" },
  { id: "laser-printers", label: "Laser Printers" },
  { id: "inkjet-printers", label: "Inkjet Printers" },
  { id: "ink-toner", label: "Ink & Toner" },
];

export const brands = ["All Brands", "HP", "Canon", "Epson", "Brother"];

export const products = [
  {
    id: "hp-laserjet-pro-mfp-3101fdwe",
    name: "HP LaserJet Pro MFP 3101fdwe All-in-One Wireless Monochrome Printer",
    brand: "HP",
    category: "laser-printers",
    usageCategory: ["Office"],
    technology: ["Laser"],
    allInOneType: ["Multifunction"],
    price: 269.99,
    originalPrice: 329.99,
    rating: 4.8,
    reviewsCount: 142,
    inStock: true,  
    stockCount: 18,
    badge: "Best Seller",
    image: "/hp-printer4.png",
    fallbackColor: "#024AD8",
    shortDesc: "Fast black-and-white printing, automatic two-sided scanning, copy, and secure Wi-Fi for busy home offices and small teams.",
    features: [
      "Print speeds up to 35 ppm",
      "Automatic 2-sided printing & scanning",
      "Dual-band Wi-Fi with self-healing",
      "Includes 3 months of HP Instant Ink",
    ],
    specs: {
      printSpeed: "Up to 35 ppm (Black)",
      connectivity: "Dual-band Wi-Fi, Ethernet, USB 2.0, Bluetooth LE",
      trayCapacity: "250-sheet input tray",
      functions: "Print, Copy, Scan, Fax",
      warranty: "1-Year Official HP Commercial Warranty",
      resolution: "1200 x 1200 dpi",
    },
  },
  {
    id: "hp-deskjet-2855e-all-in-one",
    name: "HP DeskJet 2855e Wireless Color All-in-One Inkjet Printer",
    brand: "HP",
    category: "home-printers",
    usageCategory: ["Home"],
    technology: ["Inkjet"],
    allInOneType: ["Multifunction"],
    price: 69.99,
    originalPrice: 84.99,
    rating: 4.6,
    reviewsCount: 215,
    inStock: true,
    stockCount: 22,
    badge: "Home Favorite",
    image: "/printer-support-hero1.png",
    fallbackColor: "#0066CC",
    shortDesc: "Effortlessly print, scan, and copy everyday documents, homework, and recipes with simple mobile setup and dependable Wi-Fi.",
    features: [
      "Print, copy, scan in vibrant color",
      "Fast, reliable Wi-Fi with self-reset",
      "Easy mobile printing with the HP Smart app",
      "Made from at least 60% recycled plastic",
    ],
    specs: {
      printSpeed: "7.5 ppm (Black), 5.5 ppm (Color)",
      connectivity: "Wi-Fi 802.11b/g/n, High-speed USB 2.0",
      trayCapacity: "60-sheet input tray",
      functions: "Print, Copy, Scan",
      warranty: "1-Year Limited Hardware Warranty",
      resolution: "Up to 4800 x 1200 optimized dpi color",
    },
  },
  {
    id: "hp-officejet-pro-9125e",
    name: "HP OfficeJet Pro 9125e All-in-One Wireless Color Inkjet Commercial Printer",
    brand: "HP",
    category: "office-printers",
    usageCategory: ["Office"],
    technology: ["Inkjet"],
    allInOneType: ["Multifunction"],
    price: 289.99,
    originalPrice: 349.99,
    rating: 4.8,
    reviewsCount: 177,
    inStock: true,
    stockCount: 14,
    badge: "Office Pick",
    image: "/hp-support3.png",
    fallbackColor: "#024AD8",
    shortDesc: "Commercial-grade performance with fast color speeds, automated two-sided scanning, robust security, and smart cloud printing.",
    features: [
      "Fast color printing up to 22 ppm black / 18 ppm color",
      "Single-pass 2-sided automatic document feeder (35 sheets)",
      "HP Wolf Pro Security embedded with multi-layered defense",
      "Quiet mode for focused workspace environments",
    ],
    specs: {
      printSpeed: "22 ppm (Black), 18 ppm (Color)",
      connectivity: "Self-healing Dual-Band Wi-Fi, Gigabit Ethernet, USB",
      trayCapacity: "250-sheet input tray + 60-sheet output",
      functions: "Print, Scan, Copy, Fax",
      warranty: "Up to 2-Year HP Commercial Warranty",
      resolution: "Up to 4800 x 1200 optimized dpi",
    },
  },
  {
    id: "hp-smart-tank-7602",
    name: "HP Smart Tank 7602 Wireless All-in-One Supertank Color Printer",
    brand: "HP",
    category: "inkjet-printers",
    usageCategory: ["Home", "Office"],
    technology: ["Inkjet"],
    allInOneType: ["Multifunction"],
    price: 329.99,
    originalPrice: 389.99,
    rating: 4.9,
    reviewsCount: 310,
    inStock: true,
    stockCount: 16,
    badge: "Best Supertank",
    image: "/printer-support-hero.png",
    fallbackColor: "#0052CC",
    shortDesc: "Cartridge-free printing with up to 2 years of Original HP Ink included. High-capacity tanks, magic touch screen, and automatic 2-sided printing.",
    features: [
      "Includes up to 12,000 black or 8,000 color pages of ink",
      "Automatic two-sided printing and 35-page ADF",
      "Intuitive Magic Touch display guides you through tasks",
      "Dual-band Wi-Fi with self-healing and BLE",
    ],
    specs: {
      printSpeed: "15 ppm (Black), 9 ppm (Color)",
      connectivity: "Dual-band Wi-Fi, Ethernet, USB 2.0, Bluetooth LE",
      trayCapacity: "250-sheet paper tray",
      functions: "Print, Scan, Copy, Fax",
      warranty: "2-Year Limited Manufacturer Warranty",
      resolution: "4800 x 1200 optimized dpi",
    },
  },
  {
    id: "hp-laserjet-m209dw",
    name: "HP LaserJet M209dw High-Speed Compact Wireless Monochrome Printer",
    brand: "HP",
    category: "laser-printers",
    usageCategory: ["Home", "Office"],
    technology: ["Laser"],
    allInOneType: ["Single Function"],
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.7,
    reviewsCount: 168,
    inStock: true,
    stockCount: 20,
    badge: "Compact Laser",
    image: "/hp-support2.png",
    fallbackColor: "#003399",
    shortDesc: "Fastest two-sided printing in its class with reliable dual-band Wi-Fi, compact footprint, and legendary HP laser quality.",
    features: [
      "Speedy two-sided printing up to 30 ppm",
      "Compact footprint fits seamlessly on small desks",
      "Smart-guided lighting provides intuitive status feedback",
      "High-speed dual-band Wi-Fi with auto-reset",
    ],
    specs: {
      printSpeed: "Up to 30 ppm (Black)",
      connectivity: "Dual-band Wi-Fi 802.11b/g/n, Fast Ethernet, Hi-Speed USB",
      trayCapacity: "150-sheet input tray",
      functions: "High-Speed Laser Printing",
      warranty: "1-Year Official HP Commercial Warranty",
      resolution: "600 x 600 dpi",
    },
  },
  {
    id: "hp-envy-photo-7975",
    name: "HP Envy Photo 7975 All-in-One Wireless Color Photo Printer",
    brand: "HP",
    category: "home-printers",
    usageCategory: ["Home"],
    technology: ["Inkjet"],
    allInOneType: ["Multifunction"],
    price: 239.99,
    originalPrice: 279.99,
    rating: 4.8,
    reviewsCount: 184,
    inStock: true,
    stockCount: 12,
    badge: "Photo Specialist",
    image: "/hp-printer4.png",
    fallbackColor: "#024AD8",
    shortDesc: "Stunning true-to-life borderless photos and crisp documents with dedicated photo paper tray and advanced mobile connectivity.",
    features: [
      "Dedicated photo paper tray with automatic paper detection",
      "Stunning true-to-life borderless photos up to 8.5 x 11",
      "Automatic 2-sided document printing & scanning",
      "SD card slot for direct camera memory printing",
    ],
    specs: {
      printSpeed: "15 ppm (Black), 10 ppm (Color)",
      connectivity: "Wi-Fi, Bluetooth LE, USB 2.0, SD Card Slot",
      trayCapacity: "125-sheet main tray + 15-sheet photo tray",
      functions: "Print, Scan, Copy, Web",
      warranty: "1-Year HP Limited Warranty",
      resolution: "4800 x 1200 dpi",
    },
  },
  {
    id: "hp-80a-black-toner-cf280a",
    name: "HP 80A Black Original LaserJet Toner Cartridge (CF280A)",
    brand: "HP",
    category: "ink-toner",
    usageCategory: ["Office"],
    technology: ["Laser"],
    allInOneType: [],
    price: 163.99,
    originalPrice: 189.99,
    rating: 4.9,
    reviewsCount: 420,
    inStock: true,
    stockCount: 30,
    badge: "Genuine HP Toner",
    image: "/customer-care.jpg",
    fallbackColor: "#0137a7",
    shortDesc: "Authentic Original HP 80A black toner engineered for crisp, sharp monochrome laser output, dependable duty cycles, and anti-fraud security.",
    features: [
      "Prints up to 2,560 pages with professional clarity",
      "Built-in tamper-resistant cartridge chips",
      "Zero smudging with precision-melt spherical toner particles",
      "HP Planet Partners free closed-loop cartridge recycling",
    ],
    specs: {
      pageYield: "Approx. 2,560 pages (ISO/IEC 19752)",
      compatibility: "HP LaserJet Pro 400 M401, M425 MFP series",
      color: "Monochrome Black",
      warranty: "HP Premium Protection Warranty",
    },
  },
  {
    id: "hp-67xl-high-yield-combo-ink",
    name: "HP 67XL High-Yield Black & Tri-Color Original Ink Cartridges Combo",
    brand: "HP",
    category: "ink-toner",
    usageCategory: ["Home"],
    technology: ["Inkjet"],
    allInOneType: [],
    price: 54.99,
    originalPrice: 62.99,
    rating: 4.8,
    reviewsCount: 389,
    inStock: true,
    stockCount: 35,
    badge: "Genuine HP Ink",
    image: "/svg-icon.png",
    fallbackColor: "#024AD8",
    shortDesc: "High-capacity Original HP Ink cartridges formulated to deliver vibrant photos and crisp, clean everyday documents.",
    features: [
      "Up to 2x more prints compared to standard cartridges",
      "Fade-resistant pigments for long-lasting archival quality",
      "Recycled plastic construction with free closed-loop recycling",
      "Smart ink level tracking alerts before you run out",
    ],
    specs: {
      pageYield: "Black ~240 pages, Tri-Color ~200 pages",
      compatibility: "HP ENVY 6000, 6400 series, DeskJet 2700, 4100 series",
      colors: "1 Black XL + 1 Tri-Color XL Cartridge",
      warranty: "HP Ink & Toner Quality Guarantee",
    },
  },
  {
    id: "hp-902xl-high-yield-pack",
    name: "HP 902XL Black & Cyan/Magenta/Yellow High Yield 4-Pack Original Ink (T0A39AN)",
    brand: "HP",
    category: "ink-toner",
    usageCategory: ["Office"],
    technology: ["Inkjet"],
    allInOneType: [],
    price: 118.89,
    originalPrice: 134.99,
    rating: 4.8,
    reviewsCount: 260,
    inStock: true,
    stockCount: 25,
    badge: "High Yield Pack",
    image: "/svg-icon.png",
    fallbackColor: "#0066CC",
    shortDesc: "Authentic high-yield HP 902XL four-cartridge multipack for standout business documents and sharp, smudge-resistant color presentations.",
    features: [
      "Yields up to 825 black pages and 825 color pages",
      "Resists water, smearing, and highlighter bleed",
      "Original HP security chip prevents counterfeit ink damage",
      "Optimized for high-volume office workflows",
    ],
    specs: {
      pageYield: "Black ~825 pages, CMY ~825 pages each",
      compatibility: "HP OfficeJet 6950, 6954, OfficeJet Pro 6960, 6968, 6978 series",
      colors: "Black, Cyan, Magenta, Yellow",
      warranty: "HP Ink Quality Warranty",
    },
  },
];
